/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uv.programa07cc.DAOVenta;
import org.uv.programa07cc.DetalleVenta;
import org.uv.programa07cc.Venta;

/**
 *
 * @author zS20006736
 */
public class Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }
    private DAOVenta dao = new DAOVenta();
    private Double total = 0.0;
    private int i = 0;
    String message = "¿Agregar otro producto?";
    String messageDelete = "¿Esta seguro de que desea eliminar esta compra?";
    Object[] options = {"Aceptar", "Terminar"};
    Long ID = 0L;
    Venta venta = new Venta();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelVender = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldPrecioVender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextFieldDesVender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextFieldCantidadVender = new javax.swing.JTextField();
        jButtonAgregarVender = new javax.swing.JButton();
        PanelActualizar = new javax.swing.JPanel();
        LabelDesAct = new javax.swing.JLabel();
        TextFieldPrecioAct = new javax.swing.JTextField();
        LabelPrecioAct = new javax.swing.JLabel();
        TextFieldDesAct = new javax.swing.JTextField();
        LabelCantidadAct = new javax.swing.JLabel();
        TextFieldCantidadAct = new javax.swing.JTextField();
        LabelIDAct = new javax.swing.JLabel();
        TextFielIDAct = new javax.swing.JTextField();
        jButtonComprobar = new javax.swing.JButton();
        jButtonAgregarAct = new javax.swing.JButton();
        LabelReferencia = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDBuscar = new javax.swing.JTextField();
        jButtonBuscarID = new javax.swing.JButton();
        jRadioButtonAll = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jLabelDetalle = new javax.swing.JLabel();
        jComboBoxID = new javax.swing.JComboBox<>();
        PanelDelete = new javax.swing.JPanel();
        LabelIDDelete = new javax.swing.JLabel();
        TextFieldDelete = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setClosable(true);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("DESCRIPCION:");

        TextFieldPrecioVender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("PRECIO:");

        TextFieldDesVender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("CANTIDAD:");

        TextFieldCantidadVender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonAgregarVender.setText("AGREGAR");
        jButtonAgregarVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVenderLayout = new javax.swing.GroupLayout(PanelVender);
        PanelVender.setLayout(PanelVenderLayout);
        PanelVenderLayout.setHorizontalGroup(
            PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVenderLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVenderLayout.createSequentialGroup()
                        .addGroup(PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldPrecioVender)
                            .addComponent(TextFieldDesVender)
                            .addComponent(TextFieldCantidadVender, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PanelVenderLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButtonAgregarVender, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addGap(141, 141, 141)))
                .addGap(62, 62, 62))
        );
        PanelVenderLayout.setVerticalGroup(
            PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVenderLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVenderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelVenderLayout.createSequentialGroup()
                        .addComponent(TextFieldDesVender)
                        .addGap(1, 1, 1)))
                .addGap(36, 36, 36)
                .addGroup(PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextFieldPrecioVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(PanelVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextFieldCantidadVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButtonAgregarVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Vender", PanelVender);

        LabelDesAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelDesAct.setText("DESCRIPCION:");

        TextFieldPrecioAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        LabelPrecioAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelPrecioAct.setText("PRECIO:");

        TextFieldDesAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        LabelCantidadAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelCantidadAct.setText("CANTIDAD:");

        TextFieldCantidadAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        LabelIDAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelIDAct.setText("ID:");

        TextFielIDAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        jButtonAgregarAct.setText("AGREGAR");
        jButtonAgregarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActActionPerformed(evt);
            }
        });

        LabelReferencia.setText("Editando venta: ID ");

        javax.swing.GroupLayout PanelActualizarLayout = new javax.swing.GroupLayout(PanelActualizar);
        PanelActualizar.setLayout(PanelActualizarLayout);
        PanelActualizarLayout.setHorizontalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActualizarLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelIDAct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(TextFielIDAct, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelPrecioAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelDesAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCantidadAct, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldPrecioAct)
                            .addComponent(TextFieldDesAct)
                            .addComponent(TextFieldCantidadAct, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60))))
            .addGroup(PanelActualizarLayout.createSequentialGroup()
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButtonAgregarAct))
                    .addGroup(PanelActualizarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(167, 167, 167)))
                .addGap(206, 206, 206))
        );
        PanelActualizarLayout.setVerticalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelActualizarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDAct)
                    .addComponent(TextFielIDAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDesAct)
                    .addComponent(TextFieldDesAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPrecioAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrecioAct))
                .addGap(26, 26, 26)
                .addGroup(PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCantidadAct)
                    .addComponent(TextFieldCantidadAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButtonAgregarAct)
                .addGap(54, 54, 54)
                .addComponent(LabelReferencia)
                .addContainerGap())
        );

        LabelDesAct.setVisible(false);
        TextFieldPrecioAct.setVisible(false);
        LabelPrecioAct.setVisible(false);
        TextFieldDesAct.setVisible(false);
        LabelCantidadAct.setVisible(false);
        TextFieldCantidadAct.setVisible(false);
        jButtonAgregarAct.setVisible(false);
        LabelReferencia.setVisible(false);

        jTabbedPane1.addTab("Actualizar", PanelActualizar);

        jLabel1.setText("ID:");
        jLabel1.setToolTipText("");

        jButtonBuscarID.setText("Buscar");
        jButtonBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarIDActionPerformed(evt);
            }
        });

        jRadioButtonAll.setText("Ver todo");
        jRadioButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAllActionPerformed(evt);
            }
        });

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVentas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableVentas.setEnabled(false);
        jTableVentas.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableVentas);
        if (jTableVentas.getColumnModel().getColumnCount() > 0) {
            jTableVentas.getColumnModel().getColumn(0).setHeaderValue("ID");
            jTableVentas.getColumnModel().getColumn(1).setHeaderValue("Fecha");
            jTableVentas.getColumnModel().getColumn(2).setHeaderValue("Monto");
        }

        jLabelDetalle.setText("Ver a detalle:");

        jComboBoxID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonBuscarID)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAll)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDetalle)
                    .addComponent(jComboBoxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarID)
                    .addComponent(jRadioButtonAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabelDetalle.setVisible(false);
        jComboBoxID.setVisible(false);

        jTabbedPane1.addTab("Buscar", PanelBuscar);

        LabelIDDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelIDDelete.setText("ID:");

        TextFieldDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDeleteLayout = new javax.swing.GroupLayout(PanelDelete);
        PanelDelete.setLayout(PanelDeleteLayout);
        PanelDeleteLayout.setHorizontalGroup(
            PanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeleteLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(LabelIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextFieldDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDeleteLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        PanelDeleteLayout.setVerticalGroup(
            PanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeleteLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(PanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIDDelete))
                .addGap(36, 36, 36)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(147, 147, 147))
        );

        jTabbedPane1.addTab("Eliminar Venta", PanelDelete);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarVenderActionPerformed
        DetalleVenta dt = new DetalleVenta();
        if (i == 0) {
            Date fecha = Date.from(Instant.now());
            venta.setFecha(new java.sql.Date(fecha.getTime()));
        }
        dt.setDescripcion(TextFieldDesVender.getText());
        dt.setCantidad(Double.parseDouble(TextFieldCantidadVender.getText()));
        dt.setPrecio(Double.parseDouble(TextFieldPrecioVender.getText()));
        dt.setSubtotal(dt.getCantidad() * dt.getPrecio());
        dt.setVenta(venta);
        total += dt.getSubtotal();
        venta.getDetalle().add(dt);
        int opc = JOptionPane.showOptionDialog(this, message, "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opc != JOptionPane.YES_OPTION) {
            venta.setMonto(total);
            dao.create(venta);
            venta.limpiar();
            total=0.0;
            i = 0;
        }
        TextFieldCantidadVender.setText("");
        TextFieldDesVender.setText("");
        TextFieldPrecioVender.setText("");
        i++;
    }//GEN-LAST:event_jButtonAgregarVenderActionPerformed

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
        Venta ventaBuscada = dao.findById(Long.parseLong(TextFielIDAct.getText()));
        if (ventaBuscada != null) {
            LabelIDAct.setVisible(false);
            TextFielIDAct.setVisible(false);
            jButtonComprobar.setVisible(false);
            LabelCantidadAct.setVisible(true);
            LabelDesAct.setVisible(true);
            LabelPrecioAct.setVisible(true);
            TextFieldCantidadAct.setVisible(true);
            TextFieldDesAct.setVisible(true);
            TextFieldPrecioAct.setVisible(true);
            jButtonAgregarAct.setVisible(true);
            LabelReferencia.setVisible(true);
            LabelReferencia.setText("Editando venta: " + ventaBuscada.getIdVenta());
            ID = ventaBuscada.getIdVenta();
        }
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonAgregarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActActionPerformed
        DetalleVenta dt = new DetalleVenta();
        if (i == 0) {
            Date fecha = Date.from(Instant.now());
            venta.setFecha(new java.sql.Date(fecha.getTime()));
        }
        dt.setDescripcion(TextFieldDesAct.getText());
        dt.setCantidad(Double.parseDouble(TextFieldCantidadAct.getText()));
        dt.setPrecio(Double.parseDouble(TextFieldPrecioAct.getText()));
        dt.setSubtotal(dt.getCantidad() * dt.getPrecio());
        dt.setVenta(venta);
        total += dt.getSubtotal();
        venta.getDetalle().add(dt);
        int opc = JOptionPane.showOptionDialog(this, message, "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opc != JOptionPane.YES_OPTION) {
            venta.setMonto(total);
            dao.update(ID, venta);
            venta.limpiar();
            i = 0;
        }
        TextFieldCantidadAct.setText("");
        TextFieldDesAct.setText("");
        TextFieldPrecioAct.setText("");
        i++;
    }//GEN-LAST:event_jButtonAgregarActActionPerformed

    private void jRadioButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllActionPerformed
        if (jRadioButtonAll.isSelected()) {
            List<Venta> ventas = dao.findAll();
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            for (Venta v : ventas) {
                comboBoxModel.addElement(v.getIdVenta().toString());
            }
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("ID");
            modelo.addColumn("Monto");
            modelo.addColumn("Fecha");

            for (Venta venta : ventas) {
                Object[] fila = new Object[3];
                fila[0] = venta.getIdVenta();
                fila[1] = venta.getMonto();
                fila[2] = venta.getFecha();
                modelo.addRow(fila);
            }

            jComboBoxID.setModel(comboBoxModel);
            jTableVentas.setModel(modelo);
            jLabelDetalle.setVisible(true);
            jComboBoxID.setVisible(true);

        }
    }//GEN-LAST:event_jRadioButtonAllActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int opc = JOptionPane.showOptionDialog(this, messageDelete, "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opc == JOptionPane.YES_OPTION) {
            dao.delete(Long.parseLong(TextFieldDelete.getText()));
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarIDActionPerformed
        Venta ventaBuscada = dao.findById(Long.parseLong(jTextFieldIDBuscar.getText()));
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Monto");
        modelo.addColumn("Fecha");

        Object[] fila = new Object[3];
        fila[0] = ventaBuscada.getIdVenta();
        fila[1] = ventaBuscada.getMonto();
        fila[2] = ventaBuscada.getFecha();
        modelo.addRow(fila);

        jTableVentas.setModel(modelo);
    }//GEN-LAST:event_jButtonBuscarIDActionPerformed

    private void jComboBoxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDActionPerformed
        String mensaje = "~~~~~Ventas Detalladas~~~~~\n";
        Venta venta = dao.findById(Long.parseLong((String) jComboBoxID.getSelectedItem()));
        for (DetalleVenta dt : venta.getDetalle()) {
            mensaje += "ID: " + dt.getIdProducto() + "\n";
            mensaje += "Descripción: " + dt.getDescripcion() + "\n";
            mensaje += "Precio: " + dt.getPrecio() + "\n";
            mensaje += "Cantidad: " + dt.getCantidad() + "\n";
            mensaje += "Subtotal: " + dt.getSubtotal() + "\n\n";
            i++;
        }
        JOptionPane.showMessageDialog(null, mensaje, "ID Venta: " + venta.getIdVenta(), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jComboBoxIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCantidadAct;
    private javax.swing.JLabel LabelDesAct;
    private javax.swing.JLabel LabelIDAct;
    private javax.swing.JLabel LabelIDDelete;
    private javax.swing.JLabel LabelPrecioAct;
    private javax.swing.JLabel LabelReferencia;
    private javax.swing.JPanel PanelActualizar;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelDelete;
    private javax.swing.JPanel PanelVender;
    private javax.swing.JTextField TextFielIDAct;
    private javax.swing.JTextField TextFieldCantidadAct;
    private javax.swing.JTextField TextFieldCantidadVender;
    private javax.swing.JTextField TextFieldDelete;
    private javax.swing.JTextField TextFieldDesAct;
    private javax.swing.JTextField TextFieldDesVender;
    private javax.swing.JTextField TextFieldPrecioAct;
    private javax.swing.JTextField TextFieldPrecioVender;
    private javax.swing.JButton jButtonAgregarAct;
    private javax.swing.JButton jButtonAgregarVender;
    private javax.swing.JButton jButtonBuscarID;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxID;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDetalle;
    private javax.swing.JRadioButton jRadioButtonAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextFieldIDBuscar;
    // End of variables declaration//GEN-END:variables
}
